* Fonološka analiza slovenske literature

** Osnovna ideja in viri podatkov

Osnovna ideja projektne naloge je fonološka primerjava različnih del, objavljenih v slovenskem jeziku. V okviru tega bom uporabil naslednje vire podatkov:

- Zbrana baza podatkov o poudarjenosti zlogov v besedah, dostopna na repozitoriju CLARIN.SI: https://www.clarin.si/repository/xmlui/handle/11356/1186
- Vsebina raznih literarnih besedil iz https://sl.wikisource.org
- Metapodatki o besedilih, dostopni na https://dlib.si in/ali https://plus.cobbis.net

Baza podatkov o poudarjenosti zlogov ni popolnoma natančna; avtorji v opisu podajajo 88.5% pravilnost.

*** Količina podatkov

Wikivir poroča 15.617 literarnih del, zaradi različnih faktorjev (npr. dlib ne hrani metapodatkov za vsa ta dela) pa bo dejansko število analiziranih del manjše in znano šele po zbiranju podatkov. Metapodatki literarnega dela bodo vsebovali naslednja polja:
- vir dela (knjiga/časopis/...)
- tip dela (proza/drama/...)
- avtor
- leto izdaje
- podatki o založniku

** Delovna vprašanja
- Ali tudi proza in dramatika vsebujeta ritmično strukturo?
- Ali posamezen avtor/založnik preferira neko stopico?
- Ali je ritmična struktura odvisna od leta izdaje dela?

* Pridobivanje podatkov

Prevzemanje podatkov iz spleta se izvaja z datoteko =prevzemi_podatke.py=, razen datoteke o poudarjenosti zlogov v besedah, ki se prevzame ročno, dekompresira in postavi v podmapo =podatki/=. Naslednji skript naredi prav to:
#+begin_src
  mkdir obdelani_podatki
  mkdir podatki
  cd podatki
  curl --remote-name-all https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1186{/accented_sloleks2.xml.zip,/accented_sloleks.zip}
  unzip accented_sloleks2.xml.zip
#+end_src

Datoteka =prevzemi_podatke.py= prevzemanje izvaja v treh fazah: (uporabi =--prva-faza=, =--druga-faza=, =--tretja-faza= oz. =--vse-faze=)
- V prvi fazi se sprehodi skozi seznam vseh člankov na wikiviru in si shrani povezave. Prva faza najde 21.214 povezav; nekatere od teh povezav pa vsebujejo prazne članke, ali pa preusmerijo na članek o avtorju. Vse povezave so shranjene v datoteko =podatki/literarne_strani=
- Druga faza pridobi vsebino člankov vseh najdenih povezav. Vsebine shrani v datoteke oblike =podatki/stran00000=. Članke nato filtriramo po vsebini in kategorijah; na koncu ohranimo 14.742 člankov, za 10.193 pa lahko najdemo tudi letnico. Naslov, avtorja, vsebino in letnico shranimo v =obdelani_podatki/podatki.csv=, kategorije pa posebaj v =obdelani_podatki/kategorije.csv=. Poleg tega se ustvari datoteka =podatki/viri.csv=, ki vsebuje povezave na morebitne dodatne vire (dlib/cobbis)
- Tretja faza preišče vse strani iz datoteke =podatki/viri.csv=, in si zapiše "vir" literarnega dela - če je knjiga, članek v časopisu ipd. Te vire shrani v =obdelani_podatki/viri.csv=
